name: test

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

# 同じワークフロー/同じブランチで実行中ジョブがあれば自動停止させる
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  go:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: make
        working-directory: webapp/go
