name: test

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

# 同じワークフロー/同じブランチで実行中ジョブがあれば自動停止させる
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  go:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'webapp/go/go.mod'

      - run: make
        working-directory: webapp/go

  sql:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - run: pip install sqlfluff

      - run: sqlfluff lint 0_Schema.sql --dialect=mysql -e LT01,LT05,RF04
        working-directory: webapp/mysql/db
